# [29459](https://github.com/bitcoin/bitcoin/pull/29459) test: check_mempool_result negative feerate

Adds a test to `test/functional/mempool_accept.py` that `testmempoolaccept`
raises `RPC_TYPE_ERROR` (-3) with the message `"Amount out of range"` when
passed a negative `maxfeerate`. Here's how `testmempoolaccept` parses `maxfeerate`:

```cpp
const CFeeRate max_raw_tx_fee_rate{ParseFeeRate(self.Arg<UniValue>(1))};
```

`ParseFeeRate`:

```cpp
CFeeRate ParseFeeRate(const UniValue& json)
{
    CAmount val{AmountFromValue(json)};
    if (val >= COIN) throw JSONRPCError(RPC_INVALID_PARAMETER, "Fee rates larger than or equal to 1BTC/kvB are not accepted");
    return CFeeRate{val};
}
```
And the function that throws the error: `AmountFromValue`:

```cpp
CAmount AmountFromValue(const UniValue& value, int decimals)
{
    if (!value.isNum() && !value.isStr())
        throw JSONRPCError(RPC_TYPE_ERROR, "Amount is not a number or string");
    CAmount amount;
    if (!ParseFixedPoint(value.getValStr(), decimals, &amount))
        throw JSONRPCError(RPC_TYPE_ERROR, "Invalid amount");
    if (!MoneyRange(amount))
        throw JSONRPCError(RPC_TYPE_ERROR, "Amount out of range");
    return amount;
}
```

And finally, the range logic`

```cpp
inline bool MoneyRange(const CAmount& nValue) { return (nValue >= 0 && nValue <= MAX_MONEY); }
```

## Notes
- Maybe a check that we don't exceed the upper bound `MAX_MONEY` should be added.
- Maybe add the same tests to `sendrawtransaction` for `maxfeerate` and `maxburnamount`.
